---
- name: ensure oinkmaster is configured to download suricata rules
  lineinfile:
    dest: /etc/oinkmaster.conf
    line: url = http://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz
    state: present
