---
- name: ensure suricata dependency packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - oinkmaster
    - python-software-properties

- name: ensure suricata repository is enabled
  apt_repository: 
    repo: ppa:oisf/suricata-stable
    update_cache: yes
    state: present

- name: ensure suricata packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - suricata

- name: patch suricata init to work with recent kernels
  lineinfile:
    dest: /etc/init.d/suricata
    regexp: "^if [ ! -e /proc/net/netfilter/nf_queue ]; then"
    line: "if [ ! -e /proc/net/netfilter/nfnetlink_queue ]; then"
    state: present

